### ISSUE TITLE
tzinfo error with version 0.10.0

### ISSUE THREAD

**Issue by bradstallion** [alpacahq/alpaca-backtrader-api#107]
with paper trading live (tested with strategy_sma_crossover.py):

  File ".../alpaca_backtrader_api/alpacastore.py", line 405, in _t_candles
    cdl = self.get_aggs_from_alpaca(dataname,
  File ".../alpaca_backtrader_api/alpacastore.py", line 659, in get_aggs_from_alpaca
    response = _iterate_api_calls()
  File ".../alpaca_backtrader_api/alpacastore.py", line 590, in _iterate_api_calls
    if earliest_sample <= pytz.timezone(NY).localize(start):
  File ".../pytz/tzinfo.py", line 318, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)

Version 0.8.0 worked.
Thanks

**Comment by Mou97** [comment]
I'm having the same issues, but it works just fine outside the virtual env.

**Comment by belarusrulez** [comment]
I have the same issue. Brand new python env.

**Comment by shlomikushchi** [comment]
Hi, the issue is fixed. 
you could install the fix directly from github (until we release a new version)
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api`
