### ISSUE TITLE
Samples are incorrect

### ISSUE THREAD

**Issue by mtucker502** [alpacahq/alpaca-backtrader-api#111]
Specifically strategy_sma_crossover.py. The PAPER trading if statements are reversed.

**Comment by mtucker502** [comment]
Pull #112 submitted

**Comment by shlomikushchi** [comment]
Hi,
thanks for your input.
the sample code is not wrong. the names might be confusing.
`ALPACA_PAPER` doesn't mean paper or live trading. it means backtest or forward execution.
the PAPER/LIVE trading is determined by the API keys you provide.
I will modify the name of the variable to `IS_BACKTEST` to make it more clear.

**Comment by shlomikushchi** [comment]
https://github.com/alpacahq/alpaca-backtrader-api/commit/c6b6ad4ad1c3dd2abbd7fc366aee9c73919d0551
