### ISSUE TITLE
ERROR:root:error while consuming ws messages: Invalid Alpaca API credentials, Failed to authenticate: {'stream': 'authorization', 'data': {'action': 'authenticate', 'message': 'access key verification failed', 'status': 'unauthorized'}}

### ISSUE THREAD

**Issue by ltorres6** [alpacahq/alpaca-backtrader-api#116]
Hi -- I get authentication errors when using paper api credentials and setting 
`IS_BACKTEST=False 
IS_LIVE=False
and USE_POLYGON=False`

Is a live account required to paper trade? I wish to use my paper trade account to simulate trading. 
I can get past the authentication issues if I use my live account api, however I don't see how I can paper trade with those credentials even with is_backtest and is_live set to false. 

I am on the most recent version of alpaca-backtrader-api (installed via pip install git+https://github.com/alpacahq/alpaca-backtrader-api)

Thanks in advance for your help!

**Comment by shlomikushchi** [comment]
you have different credentials for live and for paper.
you are probably trying to paper trade with your live keys.
make sure you use the right keys

**Comment by ltorres6** [comment]
Closing. I was using the right keys, but the logic in the samples needs a negation. I was trying to live trade instead of paper trade. I have submitted a pull request to fix the samples.
