### ISSUE TITLE
Skipping range of dates on historical data with Polygon data feed

### ISSUE THREAD

**Issue by x777** [alpacahq/alpaca-backtrader-api#117]
```
pip freeze | grep alpaca
alpaca-backtrader-api==0.7.1
alpaca-trade-api==0.46
```

Data feed - polygon.io. Premium.

Settings of data feed:
```
DataFactory = store.getdata  
    data = DataFactory(
        dataname=ticker,
        tz=timezone,
        timeframe=bt.TimeFrame.Minutes,
        compression=1,
        fromdate=pd.Timestamp(args.start),
        sessionstart=datetime.time(9, 30),
        sessionend=datetime.time(16, 00),
        historical=True)
```

When I try to test with old versions of packages some basic strategy, I figured that it starts from "fromdate" date, but then it skips all dates and jumps to the current last date. I am sure that data exists in the skipped range.

**Comment by x777** [comment]
```
pip freeze | grep alpaca
alpaca-backtrader-api==0.8.0
alpaca-trade-api==0.48
```
Same with this version. But when I disabled 'usePolygon=False' it's starting to work fine. But Alpaca data feed is not best for my goals.

```
store = alpaca_backtrader_api.AlpacaStore(
        key_id=ALPACA_API_KEY,
        secret_key=ALPACA_SECRET_KEY,
        paper=ALPACA_PAPER,
        usePolygon=False
    )
```

**Comment by shlomikushchi** [comment]
I fixed this issue in v0.9.5

**Comment by x777** [comment]
> I fixed this issue in v0.9.5

In this version possible to use polygon data feed separately alpaca real account?

**Comment by shlomikushchi** [comment]
I don't understand..
you have 2 available streams (the alpaca free stream and the polygon stream for paid accounts)

**Comment by x777** [comment]
> I don't understand..
> you have 2 available streams (the alpaca free stream and the polygon stream for paid accounts)

Ok, maybe this way not officially allowed, but it's possible to use polygon data feed without a real alpaca account. Yes, the polygon is paid account, but directly from polygon.io. 
So, my question is can I enable polygon data feed with env variable as in the previous versions?

**Comment by shlomikushchi** [comment]
yes. but with a boolean past as argument not environment variable.
you could see the example code: https://github.com/alpacahq/alpaca-backtrader-api/blob/master/sample/strategy_sma_crossover.py

**Comment by x777** [comment]
> yes. but with a boolean past as argument not environment variable.
> you could see the example code: https://github.com/alpacahq/alpaca-backtrader-api/blob/master/sample/strategy_sma_crossover.py

Thanks! But where I should enter polygon KEY in this example? Maybe I don't see...I see only for Alpaca's credentials. Or it's somewhere deep inside sources?

**Comment by shlomikushchi** [comment]
you pass it instead of the alpaca credentials

**Comment by x777** [comment]
> you pass it instead of the alpaca credentials

Oh, ok. Thank you for your help!
