### ISSUE TITLE
Initiating unauthorized trades, and API sleeping

### ISSUE THREAD

**Issue by guppykang** [alpacahq/alpaca-backtrader-api#132]
To start off, I have a funded alpaca account, and I'm using the polygon feed. I am updated on the latest 0.12.0 of alpaca-backtrader-api, and I am seeing unauthorized trades of unauthorized position sizes being sent. I'm running python 3.7. This error persists with Polygon true and false.

I have specified the sizer using the following code as well to 95%. Everything works perfectly fine on backtesting mode.
I then see positions being acquired on Alpaca that are not of the given sizer, and orders on price data that does not even exist for that given day. For example, today during market hours, NIO was above 50$ all day, but Alpaca (on paper mode) got a position at 46$. Then several other orders of different sizer that were not logged on my console were sent (were not logged either). I am then told to sleep and wait for the API to respond several times. When it reconnects, it sends yet another unauthorized and unlogged order. What could I be doing wrong here? Just to make sure, I used the strategy from the given starter code in this repo, and it still does not work. Example : 
![Screen Shot 2020-11-23 at 9 08 19 AM](https://user-images.githubusercontent.com/11686738/99994017-53782500-2d6d-11eb-9efe-5ae42e39a255.png)
If you see above, I am running it live on paper, but I see data from the 17th even though today is the 23rd. 

I am adding the data to cerebro like so : 
```
#Setup Alpaca with cerebro broker
cerebro = bt.Cerebro()
store = alpaca_backtrader_api.AlpacaStore(
    key_id=ALPACA_API_KEY,
    secret_key=ALPACA_SECRET_KEY,
    paper=(args.backtest or args.paper),
    usePolygon=True
)
DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
if args.live or args.paper:
  print("Using Alpaca API Broker")
  data0 = DataFactory(dataname=tickers['tickers'][0], timeframe=bt.TimeFrame.Minutes, historical=False, backfill_start=True)
  broker = store.getbroker()  # or just alpaca_backtrader_api.AlpacaBroker()
  cerebro.setbroker(broker)
elif args.backtest: 
  print("Backtesting")
  cerebro.broker.setcash(100000.0) 
  data0 = DataFactory(dataname=tickers['tickers'][0], historical=(args.backtest), backfill_start=True, fromdate=datetime.datetime(
    2020, 11, 18), timeframe=bt.TimeFrame.Minutes, tz=pytz.timezone('US/Eastern'))
else:
  raise RuntimeError("Bad trading mode")
cerebro.adddata(data0)

cerebro.addsizer(bt.sizers.PercentSizer, percents=95)
```

**Comment by guppykang** [comment]
I have reduced the situation to the following : 

1. Polygon is giving me data
2. The position size is an error on my side
3. Logs don't work correctly on backtrader for some odd reason 
4. alpaca-backtrader-api is not handling the usage of API calls correctly, and is thus timing out. 

I think number 1-3 is dealable, but I guess my issue is with number 4, as I've seen other users on this repo have this same issue.

**Comment by shlomikushchi** [comment]
Hi, not sure what you mean by handling the api calls correctly?
what do you see?

**Comment by guppykang** [comment]
Yes please try running the code that I provided, where Paper=True, usePolygon=True, and on Minutes timeframe. It does not work as intended. It runs on old data.

**Comment by guppykang** [comment]
```store = alpaca_backtrader_api.AlpacaStore(
    key_id=ALPACA_API_KEY,
    secret_key=ALPACA_SECRET_KEY,
    paper=True,
    usePolygon=True
)
DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
data0 = DataFactory(dataname='NIO',
                        historical=False,
                        timeframe=bt.TimeFrame.Days,
                        backfill_start=True,
                        )
broker = store.getbroker()
cerebro.setbroker(broker)
cerebro.adddata(data0)

print('Starting Portfolio Value: {}'.format(cerebro.broker.getvalue()))
cerebro.run()
print('Final Portfolio Value: {}'.format(cerebro.broker.getvalue()))
cerebro.plot()`

**Comment by guppykang** [comment]
And then print out the timestamps and price data on the next function in the strategy.

**Comment by shlomikushchi** [comment]
when you are running with paper trading the first step is get past data for your indicators.
this data is not considered live, but it still goes through your next function
it's because this is a hybrid solution between backtests and paper/live trading

this is why you see past data.
the solution is to check with backtrader - "are we live"?
you could see how you could go about this in the example code (e.g `strategy_sma_crossover.py`)
inside `notify_data` we do:
```py
        if data._getstatusname(status) == "LIVE":
            self.live_bars = True
```

then in `next()` we do:
```py
        if not self.live_bars and not IS_BACKTEST:
            # only run code if we have live bars (today's bars).
            # ignore if we are backtesting
            return
```

**Comment by guppykang** [comment]
Got it. I had a misunderstanding. Thanks. Quick question however. It seems that the historical data is loaded in one second at a time for say TSLA. Do I have to wait that long for it all go through the next() function, or is there a way to make this process faster?

**Comment by shlomikushchi** [comment]
it shouldn't take that long, but yes you need to wait for it to complete the entire load because the data stream goes through the backtrader mechanism if it's live or not

**Comment by guppykang** [comment]
Sounds good. I ran it today (the 30th), and it started backfilling from the 23rd. Took about 10 minutes per "day", does that sound right to you?

**Comment by guppykang** [comment]
I still seem to be getting the "WARNING - sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)..." whenever I start getting live data. 

This is how I'm getting the data:
```data0 = DataFactory(dataname=tickers['tickers'][0],
                          historical=False,
                          timeframe=bt.TimeFrame.Minutes,
                          backfill_start=True,
                          )
  broker = store.getbroker()
  cerebro.setbroker(broker)```
