### ISSUE TITLE
How to filter on all stocks in US

### ISSUE THREAD

**Issue by p595285902** [alpacahq/alpaca-backtrader-api#139]
Hi all, coming from QuantConnect, new to python algo world.
I am looking for a similar function as [FundamentalUniverseSelectionModel](https://www.quantconnect.com/docs/algorithm-framework/universe-selection#Universe-Selection-Fundamental-Universe-Selection).
It allows me to filter on each and every stocks available in the market and do filters on them. Such as price >$20, take top 100 dollar volume. The second half is probably achievable using YahooFinance but how do you get a full list of stocks?

I have been search for this for few days. All I see is filter on a predefined stock list.
Is this not possible?

**Comment by shlomikushchi** [comment]
Hi, this repo may help you: https://github.com/alpacahq/pipeline-live

**Comment by p595285902** [comment]
Thanks! just what I am looking for
