### ISSUE TITLE
Pandas time zone error when running the example

### ISSUE THREAD

**Issue by jeanfredericplante** [alpacahq/alpaca-backtrader-api#20]
As I run the README example, I am getting an exception from pandas, complaining about comparing tz aware and naive objects. 
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 463, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1004, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1581298739323852000
...
    "Cannot compare tz-naive and tz-aware datetime-like objects"
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects_
```
Here is the code I am running, I tried tz aware (```start_time```) or naive for the fromdate in the DataFactory object, no dice. Any idea?

```
import alpaca_backtrader_api
import backtrader as bt
from datetime import datetime, timedelta
import pandas as pd
import pytz

class SmaCross(bt.SignalStrategy):
  def __init__(self):
    sma1, sma2 = bt.ind.SMA(period=10), bt.ind.SMA(period=30)
    crossover = bt.ind.CrossOver(sma1, sma2)
    self.signal_add(bt.SIGNAL_LONG, crossover)

ALPACA_PAPER = True
cerebro = bt.Cerebro()
cerebro.addstrategy(SmaCross)

store = alpaca_backtrader_api.AlpacaStore(
    key_id=APCA_API_KEY_ID,
    secret_key=APCA_API_SECRET_KEY,
    paper=ALPACA_PAPER
)

timezone = pytz.timezone("America/Los_Angeles")
start_time = datetime.now() - timedelta(days=60)
start_time = timezone.localize(start_time)

DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
data0 = DataFactory(dataname='AAPL', historical=True, fromdate=pd.Timestamp('2018-11-15'), timeframe=bt.TimeFrame.Days)
cerebro.adddata(data0)

print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
cerebro.run()
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
cerebro.plot()

```

**Comment by jeanfredericplante** [comment]
Never mind, it seems adding tz argument in DataFactory solves this

```
timezone = pytz.timezone("America/Los_Angeles")
data0 = DataFactory(dataname='AAPL', historical=True, fromdate=pd.Timestamp('2018-11-15'), timeframe=bt.TimeFrame.Days, tz=timezone)

```

**Comment by cole-seph** [comment]
Was experiencing the same error and followed your fix which seems to get me to new errors. 
I've added in the code you've pasted above but now when I run the example I get `pytz is not defined`. I try installing pytz to see if that fixes via: `pip3 install pytz` but pip3 tells me it's already installed. Any ideas?

**Comment by jeanfredericplante** [comment]
try `import pytz`

**Comment by cole-seph** [comment]
yeah unfortunately that gets me back to the first error you encountered:
Adding `import pytz` to the top of my example, when I now run I get: 
`    "Cannot compare tz-naive and tz-aware datetime-like objects"
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects`

**Comment by cole-seph** [comment]
my entire modified script: 
`import alpaca_backtrader_api
import backtrader as bt
from datetime import datetime
import pytz

ALPACA_API_KEY = ''
ALPACA_SECRET_KEY = ''
ALPACA_PAPER = True


class SmaCross(bt.SignalStrategy):
  def __init__(self):
    sma1, sma2 = bt.ind.SMA(period=10), bt.ind.SMA(period=30)
    crossover = bt.ind.CrossOver(sma1, sma2)
    self.signal_add(bt.SIGNAL_LONG, crossover)


cerebro = bt.Cerebro()
cerebro.addstrategy(SmaCross)

store = alpaca_backtrader_api.AlpacaStore(
    key_id=ALPACA_API_KEY,
    secret_key=ALPACA_SECRET_KEY,
    paper=ALPACA_PAPER
)

if not ALPACA_PAPER:
  broker = store.getbroker()  # or just alpaca_backtrader_api.AlpacaBroker()
  cerebro.setbroker(broker)

DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
timezone = pytz.timezone("America/New_York")
data0 = DataFactory(dataname='AAPL', historical=True, fromdate=datetime(
    2015, 1, 1), timeframe=bt.TimeFrame.Days, tz=timezone)
cerebro.adddata(data0)

print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
cerebro.run()
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
cerebro.plot()
`

**Comment by jeanfredericplante** [comment]
wondering if this has to do with your pandas version, and/or python version. This is what I have on my colab notebook.
pandas version 0.25.3
python version 3.6.9 (default, Nov  7 2019, 10:44:02)

**Comment by jeanfredericplante** [comment]
Confirming this fails for me with pandas version >1, maybe try to downgrade your pandas install

**Comment by cole-seph** [comment]
phenomenal! It works with pandas version '0.25.3'
Thanks very much for your help
