### ISSUE TITLE
Invalid Polygon credentials

### ISSUE THREAD

**Issue by x777** [alpacahq/alpaca-backtrader-api#37]
`ValueError: Invalid Polygon credentials, Failed to authenticate: {'ev': 'status', 'status': 'auth_failed', 'message': 'authentication failed'}

I've found similar issues with original alpaca-trade-api-python. But what about alpaca-backtrader-api?

`

**Comment by shlomikushchi** [comment]
alpaca-backtrader-api is using alpaca-trade-api-python.

**Comment by x777** [comment]
@shlomikushchi yes, I understand. Anyway, not working today too.

**Comment by x777** [comment]
Polygon support answer:
_**> If your alpaca account is funded you should be able to access our data**_

So, if I am using paper account without funding for testing I can't use it.

**Comment by JustinGuese** [comment]
So I can set Polygon to False but it still uses Polygon? What are the alternatives?

**Comment by shlomikushchi** [comment]
no, if you set it to false you're using the alpaca data api. it's a new service
and starting today, you don't need a funded account to use it (@x777 )

**Comment by x777** [comment]
> no, if you set it to false you're using the alpaca data api. it's a new service
> and starting today, you don't need a funded account to use it (@x777 )

It's realtime as polygon too? Can you add new example with such new service? Thx!

**Comment by shlomikushchi** [comment]
will do it soon

**Comment by x777** [comment]
@shlomikushchi few minutes ago received newsletter from Alpaca about new service.
