### ISSUE TITLE
getcash() returns 0

### ISSUE THREAD

**Issue by kr011** [alpacahq/alpaca-backtrader-api#46]
Looks like alpaca broker's getcash() is returning 0. getvalue() seems to be OK.
I also want to ask what is the best way to get buying power (now that Alpaca has leverage). For now getcash doesn't even work (not sure if this is supposed to show actual cash or buying power), and I see other things like get_fundvalue() returns my 100k cash. I can't seem to get the 400k that my paper account shows as my buying power. 
I am using version 0.7.1.

**Comment by shlomikushchi** [comment]
you could use `store.oapi.get_account()` it will give you all the values at once. 
getcash() is getting the data from the backtrader wrapper not from the api.
when you try to access it, is before you got an account update (we need to fix that)
so it wasn't updated.
when doing oapi.get_account() you get the data from the alpaca servers so it will be up to date.
