### ISSUE TITLE
Stock tickers with missing data cause backtest not to run

### ISSUE THREAD

**Issue by daquilnp** [alpacahq/alpaca-backtrader-api#51]
I don't believe this issue has been addressed yet. I found this problem when running a list of stocks. ticker "BFYT" was causing me issues. It turns out ticker "BFYT" used to be ticker "HIIQ" before March 6, 2020. In the polygon api BFYT has no data before March 5th, and HIIQ has no data past March 5th. If you try to run a backtest with BFYT from September 2019 - April 2020 you will not get any errors, however, the backtest just doesn't run at all. Maybe the missing data could be filled with NaNs or something like that?

**Comment by shlomikushchi** [comment]
running a backtest with `sma_crossover_strategy.py` (example code) from 2019-09-01 until now gives this result:

![image](https://user-images.githubusercontent.com/7924802/82758180-ad635680-9ded-11ea-86fc-322c9b4c4704.png)

and the logs that start from 2020-04-20:

![image](https://user-images.githubusercontent.com/7924802/82758195-beac6300-9ded-11ea-8e64-53a18dc81517.png)

try installing the latest version and run the example code.
let me know if I am missing something

**Comment by daquilnp** [comment]
Sorry, I think something else was causing the issue
