### ISSUE TITLE
question about candle data

### ISSUE THREAD

**Issue by alias-noa** [alpacahq/alpaca-backtrader-api#56]
Sorry if not supposed to post this here I don't use Github a lot.  I was wondering how do you use 5m candles?  I saw that you can change 

```
DataFactory(dataname='AAPL', historical=True, fromdate=datetime(
            2015, 1, 1), timeframe=bt.TimeFrame.Days)
```

to Minutes instead of Days, but where do you define how many minutes?  Or can this not be done in which case I would like to request this feature :D

**Comment by shlomikushchi** [comment]
you should look it up here: https://www.backtrader.com/docu/data-resampling/data-resampling/

**Comment by alias-noa** [comment]
Thank you so much!  I was looking in the polygon api framework...it's hard to find stuff as a noob programmer when all these various frameworks are merged together (backtrader, alpaca, polygon) but i'm slowly catching on :D
