### ISSUE TITLE
Bug in broker.getvalue

### ISSUE THREAD

**Issue by ronnyli** [alpacahq/alpaca-backtrader-api#58]
I ran into an issue when trying to run `self.order_target_percent` and noticed that I was only creating SELL orders despite having an empty paper portfolio and using a positive target percentage. Digging deeper I noticed that [this line](https://github.com/mementum/backtrader/blob/master/backtrader/strategy.py#L1314) in backtrader.Strategy is necessary to determine the portfolio value for specific assets. 

I believe the issue will be fixed by modifying the `alpacabroker.getvalue` method [here](https://github.com/alpacahq/alpaca-backtrader-api/blob/master/alpaca_backtrader_api/alpacabroker.py#L149-L153) to use the `datas` argument.

**Comment by shlomikushchi** [comment]
thanks for the detailed description.
funny note: the other brokers (IB, Oanda) didn't use datas too.
you can install the fix like this:
`pip install -U git+https://github.com/alpacahq/alpaca-backtrader-api`
let me know if you have any issues with this

**Comment by ronnyli** [comment]
Thanks @shlomikushchi! Your fix looks similar to mine which I've confirmed works for my use case.

Here's my fix for comparison:
```
        if datas:
            value = 0.0
            for d in datas:
                pos = self.getposition(d)
                posval = pos.size * pos.price
                value += posval
            return value
        else:
            self.value = float(self.o.oapi.get_account().portfolio_value)
            return self.value
```

**Comment by ronnyli** [comment]
Also just tested that the latest fix worked for me 👍
