### ISSUE TITLE
Unable to Run Sample

### ISSUE THREAD

**Issue by davidkwong** [alpacahq/alpaca-backtrader-api#6]
Hello,

I am trying to run the sample but looks like the API is not working with backtrader.

I created a new conda enviroment with python 3.6 in mac and install these packages with pip

alpaca-backtrader-api     0.3                       <pip>
alpaca-trade-api          0.24                      <pip>
backtrader                1.9.69.122                <pip>

This line is showing error after I put the key.

store = alpaca_backtrader_api.AlpacaStore(
    key_id='',
    secret_key='',
    paper=True
)
<img width="987" alt="screen shot 2019-01-02 at 10 00 15 pm" src="https://user-images.githubusercontent.com/3953867/50624096-d245e980-0ed9-11e9-9a51-3cd30f4ad481.png">

Also, I uncomment alpaca_backtrader_api.AlpacaBroker()  alpaca_backtrader_api.AlpacaData and try to use them directly show authorization error even I have set this in my .bash_profile and source it.

export APCA_API_BASE_URL="https://paper-api.alpaca.markets"
export APCA_API_KEY_ID="mykeyid"
export APCA_API_SECRET_KEY="mysecret"

However, if only using alpaca_trade_api just works to prove that my environment variable setup is good.

import alpaca_trade_api as tradeapi

api = tradeapi.REST()
account = api.get_account()
print(account.status)

Do you have any ideas ?

**Comment by ndenys650** [comment]
having the same problem here. have you been able to resolve?

**Comment by albertputrapurnama** [comment]
Hi,

The reason @davidkwong's code does not work is because the code cannot read your `key_id` and `secret_key`. You will need to either one of the following ways:

1. Copy your `APCA_API_KEY_ID` and `APCA_API_SECRET_KEY` into the store initialization, or
2. You will need to load those values from the os environment. The way to do this is by the following

```python
import os
...

store = alpaca_backtrader_api.AlpacaStore(
  key_id=os.getenv('APCA_API_KEY_ID'),
  secret_key=os.getenv('APCA_API_SECRET_KEY'),
  paper=True
)
```

Hope this help @ndenys650 too!

**Comment by shlomikushchi** [comment]
work under fix: https://github.com/alpacahq/alpaca-backtrader-api/pull/22. 
it will be merged soon

**Comment by shlomikushchi** [comment]
code has been merged and a new version released. https://github.com/alpacahq/alpaca-backtrader-api/releases/tag/v0.4
