### ISSUE TITLE
AttributeError: 'Entity' object has no attribute 'symbol'

### ISSUE THREAD

**Issue by William-Ebertz** [alpacahq/alpaca-backtrader-api#67]
Hey there. I'm running a modified version of the multiple_data_strategy sample on the shared_websocket_streamer branch. It seems to work great for a couple of minutes, then hits the exception below after making a few trades. It seems like the exception caused it to lose connection to the live data stream, as it stops trading but also doesn't return to the shell. I'm happy to provide more details for troubleshooting.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_backtrader_api/streamcon_service.py", line 70, in _subscription_listener
    self.conn.run(channels)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 276, in run
    loop.run_until_complete(self.consume())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 266, in consume
    self.data_ws.consume(),
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 64, in consume
    await self._consume_task
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 76, in _consume_msg
    await self._dispatch(stream, msg)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 151, in _dispatch
    await handler(self, channel, ent)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_backtrader_api/streamcon_service.py", line 109, in on_trade
    self.q_mapping[msg.symbol].put(msg)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/entity.py", line 29, in __getattr__
    return super().__getattribute__(key)
AttributeError: 'Entity' object has no attribute 'symbol'

**Comment by shlomikushchi** [comment]
Hi
every time you see this `AttributeError: 'Entity' object has no attribute 'symbol'` it means that the data returned from the server is not the expected data (usually it means you get an error message and when trying to wrap it with an Entity this is what you get)

let's first start by making sure that you have the latest version of the python-sdk
do this:
`pip install -U git+https://github.com/alpacahq/alpaca-trade-api-python`

**Comment by shlomikushchi** [comment]
and I just pulled the latest code from the master branch into this branch.
so make sure you pull this branch too

**Comment by William-Ebertz** [comment]
Thanks, I ran the updates on the trade api and this one. It looks like it recovered from two instances of this exception, though it still crashed:

Starting Portfolio Value: 99418.14
***** DATA NOTIF: LIVE
***** DATA NOTIF: LIVE
***** DATA NOTIF: LIVE
2020-06-15T16:42:30, <alpaca_backtrader_api.alpacadata.AlpacaData object at 0x729d9030>
2020-06-15T16:42:30, Crossover below: -0.02233333333333576
2020-06-15T16:42:30, 2020-06-15 16:42:36
ERROR:root:error while consuming ws messages: 'Entity' object has no attribute 'symbol'
2020-06-15T16:42:30, Order submitted/accepted, do nothing
ERROR:root:error while consuming ws messages: 'Entity' object has no attribute 'symbol'
Traceback (most recent call last):
  File "multiple_data_strategy_days.py", line 173, in <module>
    strategy = cerebro.run(maxcpus=2)
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 1630, in _runnext
    strat._next()
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/strategy.py", line 347, in _next
    super(Strategy, self)._next()
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/lineiterator.py", line 265, in _next
    self._notify()
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/strategy.py", line 606, in _notify
    fundvalue = self.broker.fundvalue
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/broker.py", line 125, in get_fundvalue
    return self.getvalue()
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacabroker.py", line 160, in getvalue
    self.value = float(self.o.oapi.get_account().portfolio_value)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_trade_api/entity.py", line 29, in __getattr__
    return super().__getattribute__(key)
AttributeError: 'Account' object has no attribute 'portfolio_value'

**Comment by shlomikushchi** [comment]
does it happen also with the sample code? I would like to execute it locally and try and see if it happens locally too

**Comment by William-Ebertz** [comment]
I will test the sample script tomorrow. In the meantime, here's my script if you'd like to try it:

import alpaca_backtrader_api
import backtrader as bt
import datetime

# Your credentials here
ALPACA_API_KEY = ""
ALPACA_SECRET_KEY = ""
# change to True if you want to do live paper trading with Alpaca Broker.
#  False will do a back test
ALPACA_PAPER = False


class SmaCross1(bt.Strategy):
    # list of parameters which are configurable for the strategy
    params = dict(
        period=30
    )
    data_live=False
    order = None
    sma = None
    lastTradeTime = None
    tradingIntervalSeconds = 3000
    logpath = "./tradinglog.txt"

    def log(self, txt, dt=None):
        dt = dt or self.data.datetime[0]
        dt = bt.num2date(dt)
        print('%s, %s' % (dt.isoformat(), txt))
        f = open(self.logpath, "a+")
        f.write('%s %s \n' % (dt.isoformat(), txt))
        f.close()

    def notify_data(self, data, status, *args, **kwargs):
        print('*' * 5, 'DATA NOTIF:', data._getstatusname(status), *args)
        if status == data.LIVE:
            self.data_live = True

    def notify_trade(self, trade):
        self.log("placing trade for {}. at {} | target size: {} | Profit/Loss: {}".format(
            trade.getdataname(),
            trade.price,
            trade.size,
            (trade.pnl / self.broker.getvalue())))

    def notify_order(self, order):
        # 1. If order is submitted/accepted, do nothing
        
        if order.status in [order.Submitted, order.Accepted]:
            self.log("Order submitted/accepted, do nothing")
            return
            # 2. If order is buy/sell executed, report price executed
        if order.status in [order.Completed]: 
                if order.isbuy():
                    self.log('BUY EXECUTED, Price: {0:8.2f}, Size: {1:8.2f} Cost: {2:8.2f}, Comm: {3:8.2f}'.format(
                    order.executed.price,
                    order.executed.size,
                    order.executed.value,
                    order.executed.comm))
                else:
                    self.log('SELL EXECUTED, {0:8.2f}, Size: {1:8.2f} Cost: {2:8.2f}, Comm{3:8.2f}'.format(
                    order.executed.price, 
                    order.executed.size, 
                    order.executed.value,
                    order.executed.comm))
                                                                   
        elif order.status in [order.Expired, order.Canceled, order.Margin, order.Rejected]:
            self.log("Order Expired/Canceled/Margin/Rejected")

        self.order = None
        self.log("Order reset")

    def notify_store(self, msg, *args, **kwargs):
        print('*' * 5, 'STORE NOTIF:', msg)

    def stop(self):
        print('==================================================')
        print('Starting Value - %.2f' % self.broker.startingcash)
        print('Ending   Value - %.2f' % self.broker.getvalue())
        print('==================================================')

    def __init__(self):     
        # Create SMA on 2nd data
        self.sma = bt.ind.SMA(self.data1.close, period=self.p.period)
        # Create a CrossOver Signal from close an moving average
        self.signal = bt.ind.CrossOver(self.data1.close, self.sma)

    def next(self):
        # if fast crosses slow to the upside
        currentBarTime = self.data1.num2date()
        if self.order and self.lastTradeTime:
            if (currentBarTime - self.lastTradeTime).seconds > self.tradingIntervalSeconds:
                self.cancel(self.order)
                self.log("Order canceled")
            
            return
        
        if not self.data_live and ALPACA_PAPER:
            self.log("data not live, do nothing")
            return

        if self.data1.close > self.sma:
            self.log(self.data1)
            self.log("Crossover above: {}".format(self.data1.close - self.sma))
            if self.getposition(self.data2):
                #self.order = self.close(data=data2)  
                self.order = self.close(data=data2, exectype=bt.Order.Limit)
                self.lastTradeTime = self.data1.num2date()
                self.log(self.lastTradeTime)
            if not self.getposition(self.data0):
                #self.order = self.buy(data=data0)  # enter long
                self.order = self.buy(data=data0, exectype=bt.Order.Limit)
                self.lastTradeTime = self.data1.num2date()
                self.log(self.lastTradeTime)
        # in the market & cross to the downside
        if self.data1.close < self.sma:
            self.log(self.data1)
            self.log("Crossover below: {}".format(self.data1.close - self.sma))
            if self.getposition(self.data0):
                #self.order = self.close(data=data0)  # close long position
                self.order = self.close(data=data0, exectype=bt.Order.Limit)
                self.lastTradeTime = self.data1.num2date()
                self.log(self.lastTradeTime)
            if not self.getposition(self.data2):
                #self.order = self.buy(data=data2)
                self.order = self.buy(data=data2, exectype=bt.Order.Limit)
                self.lastTradeTime = self.data1.num2date()
                self.log(self.lastTradeTime)
                        
        

if __name__ == '__main__':
    cerebro = bt.Cerebro(preload=False, maxcpus=2)
    cerebro.addstrategy(SmaCross1)
    cerebro.addsizer(bt.sizers.PercentSizer, percents=1)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='Drawdown')

    store = alpaca_backtrader_api.AlpacaStore(
        key_id=ALPACA_API_KEY,
        secret_key=ALPACA_SECRET_KEY,
        paper=True,
        usePolygon=True
    )

    DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
    if ALPACA_PAPER:
        data0 = DataFactory(dataname='SSO', 
            timeframe=bt.TimeFrame.Minutes, compression=1, backfill_start=False)
        data1 = DataFactory(dataname='SPY',
            timeframe=bt.TimeFrame.Minutes, compression=1, backfill_start=False)
        data2 = DataFactory(dataname='IEF',
            timeframe=bt.TimeFrame.Minutes, compression=1, backfill_start=False)                            
        # or just alpaca_backtrader_api.AlpacaBroker()
        broker = store.getbroker()
        cerebro.setbroker(broker)

    else:
        data0 = DataFactory(dataname='SSO', historical=True, fromdate=datetime.datetime(
            2020, 5, 1), todate=datetime.datetime(2020, 6, 1), timeframe=bt.TimeFrame.Minutes, compression=1)
        data1 = DataFactory(dataname='SPY', historical=True, fromdate=datetime.datetime(
            2020, 5, 1), todate=datetime.datetime(2020, 6, 1), timeframe=bt.TimeFrame.Minutes, compression=1)
        data2 = DataFactory(dataname='IEF', historical=True, fromdate=datetime.datetime(
            2020, 5, 1), todate=datetime.datetime(2020, 6, 1), timeframe=bt.TimeFrame.Minutes, compression=1)      
    
        
    cerebro.adddata(data0)
    cerebro.adddata(data1)
    cerebro.adddata(data2)

    if not ALPACA_PAPER:
        # backtrader broker set initial simulated cash
        cerebro.broker.setcash(100000.0)

    print('Starting Portfolio Value: {}'.format(cerebro.broker.getvalue()))
    strategy = cerebro.run(maxcpus=2)
    print('Final Portfolio Value: {}'.format(cerebro.broker.getvalue()))
    print('Max Drawdown:', strategy[0].analyzers.Drawdown.get_analysis().max.drawdown)
    print('Time Underwater:', strategy[0].analyzers.Drawdown.get_analysis().max.len)
    #cerebro.plot()

**Comment by William-Ebertz** [comment]
I'll try running the sample code tomorrow. In the meantime, here's the script I'm running.

[multiple_data_strategy_mod.zip](https://github.com/alpacahq/alpaca-backtrader-api/files/4789218/multiple_data_strategy_mod.zip)

**Comment by William-Ebertz** [comment]
Hi there, confirmed that I'm getting this error on the unmodified multiple_data_strategy script as well.

**Comment by William-Ebertz** [comment]
Hey, I confirmed that I'm getting the same error on the unmodified multiple_data_strategy script as well.

**Comment by shlomikushchi** [comment]
Hi, I believe I fixed the issue.
pull from the branch again, and let me know if it works (or not)

**Comment by shlomikushchi** [comment]
Hi, any update?

**Comment by William-Ebertz** [comment]
Hey thanks for the patch, it seems to have fixed this error. However, I'm getting a new error when the multiple_data_strategy script places orders. As soon as the order is successfully placed, it quits with this message:

Starting Portfolio Value: 99419.47
2020-06-23T19:34:46, placing trade for AAPL. target size: 5
Traceback (most recent call last):
  File "multiple_data_strategy.py", line 101, in <module>
    cerebro.run()
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/cerebro.py", line 1542, in _runnext
    drets.append(d.next(ticks=False))
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/feed.py", line 407, in next
    ret = self.load()
  File "/home/pi/.local/lib/python3.7/site-packages/backtrader/feed.py", line 479, in load
    _loadret = self._load()
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacadata.py", line 302, in _load
    ret = self._load_tick(msg)
  File "/home/pi/.local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacadata.py", line 389, in _load_tick
    dtobj = datetime.utcfromtimestamp(int(msg['time']))
KeyError: 'time'

**Comment by shlomikushchi** [comment]
could you pull the branch and try again?

**Comment by William-Ebertz** [comment]
The new branch is working, several buy and sell orders completed without exceptions. Should be able to run my own script now as well, thanks.

**Comment by shlomikushchi** [comment]
closing this issue. let me know if anything else is required
