### ISSUE TITLE
Portfolio Value Deprecated

### ISSUE THREAD

**Issue by rajdua22** [alpacahq/alpaca-backtrader-api#73]
It looks like portfolio_value was deprecated from the alpaca api, but the change is yet to be represented in this library. Would it be possible to update?

**Comment by shlomikushchi** [comment]
Hi
I just ran this code

![image](https://user-images.githubusercontent.com/7924802/85228062-c6115d00-b3e9-11ea-985a-6af8f544aa3b.png)

what do you mean deprecated?

**Comment by rajdua22** [comment]
Hmm, it was seemingly not working for me. But I will try again. Thanks for the support
