### ISSUE TITLE
cerebro.broker.getvalue() returns 0

### ISSUE THREAD

**Issue by kr011** [alpacahq/alpaca-backtrader-api#8]
Hi, I have tried both my live and paper API keys. Just starting off, getvalue() and getcash() both return 0.

**Comment by jzderadicka** [comment]
> Hi, I have tried both my live and paper API keys. Just starting off, getvalue() and getcash() both return 0.

Hi, I may have a similar issue.  I was looking to get the cash of the alpaca store/broker, but when running, it appears to stay at 0.

Any help is appreciated.

**Comment by shlomikushchi** [comment]
both getcash() and getvalue() works under: https://github.com/alpacahq/alpaca-backtrader-api/pull/22

it will be merged soon

**Comment by shlomikushchi** [comment]
this issue should be resolved with the updated version on pypi.
let me know if you still encounter issues.
