### ISSUE TITLE
data not recognized by backtrader

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [alpacahq/alpaca-backtrader-api#96]
if use
`data = DataFactory(dataname='AAPL', historical=True, fromdate=datetime.datetime(2008, 1, 1), timeframe=bt.TimeFrame.Days)`
reports error
`'NoneType' object has no attribute 'isoformat'`
if use
`data = bt.feeds.YahooFinanceData(dataname='MSFT', fromdate=datetime.datetime(2011, 1, 1), todate=datetime.datetime(2019, 12, 31))`
runs fine.

**Comment by shlomikushchi** [comment]
thanks, fixed in https://github.com/alpacahq/alpaca-backtrader-api/pull/97
you can install the fixed version directly from github, until we release a new version
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api`
